#JOSE DE JESUS HERRERA PADILLA 
#INSTITUTO TECNOLOGICO DE LEON
#LABORATORIO PARA EL DESPLIGUE DE APLICACIONES

#usaremos una verion 5.7 de mysql
FROM mysql:5.7
#copiar nuestro script a la imagen
COPY ./mysql/scripts/ /docker-entrypoint-initdb.d
