#JOSE DE JESUS HERRERA PADILLA 
#INSTITUTO TECNOLOGICO DE LEON
#LABORATORIO PARA EL DESPLIGUE DE APLICACIONES
apiVersion: apps/v1  #se usa para versiones anteriores a 1.9.0
kind: Deployment
metadata:
  name: backend
  labels:
    app: bd
spec:
  selector: #permite seleccionar un conjuntos de objetos que cumplan las condiciones
    matchLabels:
      app: bd
      tier: backend
  replicas: 1 #indicas al controlador que se ejecute 1 pods
  template: #plantilla que define los containers
    metadata:
      labels:
        app: bd
        tier: backend
    spec:
      containers:
      - name: bd-mysql
        image: jjesusherrera/my-docker-mysql:v1
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: root1234
        - name: MYSQL_DATABASE
          value: webmarket
        - name: MYSQL_USER
          value: jesusherrera
        - name: MYSQL_PASSWORD
          value: jh1234
        #args: ["--defauld-authentication-plugin=mysql_native_password"]
        ports: 
        - containerPort: 3306 
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage-claim
          persistentVolumeClaim:
            claimName: mysql-pv-claim
